#
# Project:
# Module:	
# Programmer:   Brandon Tarney
# Organization:	JHU EP
# Host System:	SunOS 4
# Date Created: February 10
# Modifications:
#	$Log$
# 
# 

# Library to make (eg: libeg.a)
LIBRARY = log_mgr.a 


# Source files for LIBRARY routines
SRC	= log_mgr.c

# Master include files for libraries.
include ../../../Make_templates/Make.lib
